local M = {}

M.plugins_status = {
  ["alpha-nvim"] = true,
  ["auto-pairs"] = true,
  ["barbecue"] = true,
  ["bufferline"] = true,
  ["catppuccin"] = true,
  ["chatgpt"] = true,
  ["cmp"] = true,
  ["codi"] = true,
  ["comment"] = true,
  ["dap"] = true,
  ["emmet"] = true,
  ["font"] = true,
  ["fugitive"] = true,
  ["git"] = true,
  ["harpoon"] = true,
  ["illuminate"] = true,
  ["init"] = true,
  ["jsdoc"] = true,
  ["lsp"] = true,
  ["lualine"] = true,
  ["markdown-preview"] = true,
  ["null-ls"] = true,
  ["nvim-colorizer"] = true,
  ["nvim-tree"] = true,
  ["obsidian"] = true,
  ["rust"] = true,
  ["symbols-outline"] = true,
  ["telescope"] = true,
  ["toggleterm"] = true,
  ["treesitter"] = true,
  ["typescript"] = true,
  ["vifm"] = true,
  ["vim-surround"] = true,
  ["vimwiki"] = true,
  ["zen"] = true,
}

return M
